# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

export RAILS_ENV={{rails_env}}

PATH=$HOME/.rbenv/bin:$PATH:$HOME/bin

eval "$(rbenv init -)"

export PATH
