---
- name: install rbenv
  sudo: no
  git: repo={{item.repo}} dest={{item.dest}} accept_hostkey=yes
  with_items:
    - repo: git://github.com/sstephenson/rbenv.git
      dest: ~/.rbenv
    - repo: https://github.com/sstephenson/ruby-build.git
      dest: ~/.rbenv/plugins/ruby-build

- name: copy .bash_profile
  sudo: no
  template: src=ruby/bash_profile dest=~/.bash_profile mode=644

- name: install ruby dependency packages
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - libffi-dev
    - libmysqld-dev

- name: installed ruby check
  sudo: no
  shell: /bin/bash -lc "rbenv versions | grep {{ruby_version}}"
  register: ruby_installed
  ignore_errors: yes
  changed_when: false

- name: install ruby
  sudo: no
  shell: /bin/bash -lc "rbenv install {{ruby_version}} && rbenv rehash && rbenv global {{ruby_version}}"
  when: ruby_installed|failed

- name: install gems
  sudo: no
  gem: name={{item}} executable=~/.rbenv/shims/gem state=present user_install=no
  with_items:
    - bundler

